services:
  api:
    container_name: api
    profiles:
      - api
    build:
      context: .
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./.env:/opt/api/.env
    command: sh -c "cd /opt/api/ && npm run start:prod"